---
AWSTemplateFormatVersion: "2010-09-09"

Description: This template deploys a set of AWS resources needed to run the web deployment lab.

Resources:

  ###############################################################
  ### VPC and Gateways

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 172.100.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Roomreservation-VPC

  IGW:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: Roomreservation-IGW

  GatewayAttach:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  EIPNatGWA:
    DependsOn: GatewayAttach
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  EIPNatGWB:
    DependsOn: GatewayAttach
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  NatGatewayA:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt EIPNatGWA.AllocationId
      SubnetId: !Ref SubnetPublicA
      Tags:
        - Key: Name
          Value: Roomreservation-NatGWA

  NatGatewayB:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt EIPNatGWB.AllocationId
      SubnetId: !Ref SubnetPublicB
      Tags:
        - Key: Name
          Value: Roomreservation-NatGWB

  ###############################################################
  ### SUBNETs

  SubnetPublicA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: 172.100.1.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Roomreservation-PublicA

  SubnetPublicB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: 172.100.2.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Roomreservation-PublicB

  SubnetRouteTableAssociatePublicA:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublicA

  SubnetRouteTableAssociatePublicB:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublicB

  SubnetPrivateA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: 172.100.101.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Roomreservation-PrivateA

  SubnetPrivateB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: 172.100.102.0/24
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Roomreservation-PrivateB

  SubnetRouteTableAssociatePrivateA:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePrivateA
      SubnetId: !Ref SubnetPrivateA

  SubnetRouteTableAssociatePrivateB:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTablePrivateB
      SubnetId: !Ref SubnetPrivateB

  ###############################################################
  ### ROUTETABLEs

  RouteTablePublic:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Roomreservation-Public

  RouteTablePrivateA:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Roomreservation-PrivateA

  RouteTablePrivateB:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Roomreservation-PrivateB

  ###############################################################
  ### ROUTEs

  PublicDefaultRoute:
    Type: "AWS::EC2::Route"
    DependsOn: GatewayAttach
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RouteTablePublic

  PrivateADefaultRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayA
      RouteTableId: !Ref RouteTablePrivateA

  PrivateBDefaultRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayB
      RouteTableId: !Ref RouteTablePrivateB

  ###############################################################
  ### Security Groups

  ALBSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: Roomreservation-ALB-SG
      GroupDescription: Allow HTTP from anywhere
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: ALB-SG
      VpcId: !Ref VPC

  ECSSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: Roomreservation-ECS-SG
      GroupDescription: Allow HTTP from ALB
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSG
      Tags:
        - Key: Name
          Value: ECS-SG
      VpcId: !Ref VPC

  TASKSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: Roomreservation-TASK-SG
      GroupDescription: Allow HTTP on 8080 from anywhere
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 8080
          ToPort: 8080
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: TASK-SG
      VpcId: !Ref VPC

  ###############################################################
  ### ECS

  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: Roomreservation-Cluster
      ClusterSettings: 
        - Name: containerInsights
          Value: enabled

  MyContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: roomreservation

  ###############################################################
  ### Cloud9

  MyCloud9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 60
      InstanceType: t3.medium
      Name: fhnw-web-deployment


  ###############################################################
  ### Cloudwatch

  ECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /aws/ecs/
          - Roomreservation-Cluster
      RetentionInDays: 1

  ###############################################################
  ### ALB

  ALB:
    #DependsOn: S3LogBucketPolicy
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSG
      Subnets:
        - !Ref SubnetPublicA
        - !Ref SubnetPublicB
      Tags:
        - Key: Name
          Value: ALB
      Type: application
      IpAddressType: ipv4

  Listener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      VpcId: !Ref VPC
      Name: ecs-roomreservation-service
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: /
      HealthCheckPort: 8080
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher: 
        HttpCode: 200

    
  ###############################################################
  ### IAM

  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: LogAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                Resource: "*"


###############################################################
### Outputs
###############################################################
Outputs:
  VPC:
    Value: !Ref VPC
    Description: VPC
  IGW:
    Value: !Ref IGW
    Description: IGW
  AvailabilityZone1:
    Value: !GetAtt SubnetPrivateA.AvailabilityZone
    Export:
      Name: AvailabilityZone1
  AvailabilityZone2:
    Value: !GetAtt SubnetPrivateB.AvailabilityZone
    Export:
      Name: AvailabilityZone2
  SubnetPublicA:
    Value: !Ref SubnetPublicA
    Description: Public Subnet A Id
  SubnetPublicB:
    Value: !Ref SubnetPublicB
    Description: Public Subnet B Id
  SubnetPrivateA:
    Value: !Ref SubnetPrivateA
    Description: Private Subnet A Id
  SubnetPrivateB:
    Value: !Ref SubnetPrivateB
    Description: Private Subnet B Id
  RouteTablePublic:
    Value: !Ref RouteTablePublic
    Description: Public Route Table
  RouteTablePrivateA:
    Value: !Ref RouteTablePrivateA
    Description: Private A Route Table
  RouteTablePrivateB:
    Value: !Ref RouteTablePrivateB
    Description: Private B Route Table
  ECSCluster:
    Value: !Ref ECSCluster
    Description: ECS Cluster Name
    Export:
      Name: ECS-Cluster
  ALBSG:
    Value: !Ref ALBSG
    Description: Security Group Id that is attached to the ALB
    Export:
      Name: ALB-SG
  ALB:
    Value: !Ref ALB
    Description: Loadbalancer
    Export:
      Name: ALB
  ALBListener:
    Value: !Ref Listener
    Description: ALB Listener
    Export:
      Name: ALB-Listener
  ALBDNSName:
    Value: !GetAtt ALB.DNSName
    Description: Loadbalancer DNS Name
    Export:
      Name: ALB-DNS
  ECSTaskExecutionRole:
    Value: !Ref ECSTaskExecutionRole
    Description: ECS Task Execution Role
    Export:
      Name: ECSTaskExecutionRole